name: draco
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - clingo
  - pandas

  # development dependencies
  - poetry
  - pre-commit
  - mypy
  - pytest
  - pytest-cov
  - black
  - data-science-types
  - flake8
  - flake8-black
  - jupyterlab
  - vega_datasets
  - pip
  - pip:
      - jupyter-book
